title = "Kubernetes Training"
theme = "hugo-theme-learn"
createFromSiteMenusMain = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = false
pygmentsStyle = "dracula"
pygmentsOptions = [ 'linenos' ]
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "mine"
editURL = "https://github.com/ansilh/k8s-training-doc/tree/master/content/"
menu = [ "Introduction", "Installation" ]
showVisitedLinks = true
