title = "Kubernetes Training"
theme = "hugo-theme-learn"
createFromSiteMenusMain = true
# For search functionality
pygmentsUseClassic            = true
pygmentsCodeFences            = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses            = true
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "mine"
editURL = "https://github.com/ansilh/k8s-training-doc/tree/master/content/"
menu = [ "Introduction", "Installation", "Pods" ]
showVisitedLinks = true
