title = "Kubernetes Training"
theme = "hugo-theme-learn"
createFromSiteMenusMain = true
# For search functionality
# pygmentsUseClassic            = false
# pygmentsCodeFences            = true
# pygmentsCodeFencesGuessSyntax = true
# pygmentsUseClasses            = true
[params]
 themeVariant = "mine"
 editURL = "https://github.com/ansilh/k8s-training-doc/tree/master/content/"
 disableInlineCopyToClipBoard = true
 author = "Ansil H"
 showVisitedLinks = true
[outputs]
 home = [ "HTML", "RSS", "JSON"]
