title = "Kubernetes training"
theme = "hugo-theme-learn"
createFromSiteMenusMain = true
BaseURL = "https://k8s-school.fr/resources"
disqusShortname = "https-k8s-school-fr-training"

# For search functionality
# pygmentsUseClassic            = false
# pygmentsCodeFences            = true
# pygmentsCodeFencesGuessSyntax = true
# pygmentsUseClasses            = true

[params]
 themeVariant = "k8s-school"
 editURL = "https://github.com/k8s-school/k8s-training-doc/tree/master/content/"
 disableInlineCopyToClipBoard = true
 author = "Fabrice Jammes"
 AuthorName = "Fabrice Jammes"
 showVisitedLinks = true
 google_analytics_id = "UA-146891246-1"

[outputs]
 home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30
