title = "Kubernetes From Scratch - Ansil"
theme = "hugo-theme-learn"
createFromSiteMenusMain = true
BaseURL = "https://ansilh.com"
disqusShortname = "ansilh"
googleAnalytics = "UA-136333756-1"

# For search functionality
# pygmentsUseClassic            = false
# pygmentsCodeFences            = true
# pygmentsCodeFencesGuessSyntax = true
# pygmentsUseClasses            = true
[params]
 themeVariant = "mine"
# editURL = "https://github.com/ansilh/k8s-training-doc/tree/master/content/"
 disableInlineCopyToClipBoard = true
 author = "Ansil H"
 AuthorName = "Ansil H"
 showVisitedLinks = true
[outputs]
 home = [ "HTML", "RSS", "JSON"]
