title = "Kubernetes training"
theme = "hugo-theme-learn"
createFromSiteMenusMain = true
BaseURL = "https://k8s-school.fr/resources"
disqusShortname = "fabricejammes"
googleAnalytics = "UA-146891246-1"

# For search functionality
# pygmentsUseClassic            = false
# pygmentsCodeFences            = true
# pygmentsCodeFencesGuessSyntax = true
# pygmentsUseClasses            = true
[params]
 themeVariant = "mine"
 editURL = "https://github.com/k8s-school/k8s-training-doc/tree/master/content/"
 disableInlineCopyToClipBoard = true
 author = "Fabrice Jammes"
 AuthorName = "Fabrice Jammes"
 showVisitedLinks = true
[outputs]
 home = [ "HTML", "RSS", "JSON"]
